include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    unused_element: ignore
    directives_ordering: ignore

  exclude:
      - lib/src/version.dart
      - example/main.dart
