name: brick_oven
description: A generator to create & format bricks for mason
version: 0.1.0
homepage: https://github.com/mrgnhnt96/brick_oven
repository: https://github.com/mrgnhnt96/brick_oven

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  equatable: ^2.0.3
  file: ^6.1.2
  mason_logger: ^0.1.0-dev.4
  meta: ^1.7.0
  path: ^1.8.1
  pub_updater: ^0.2.2
  watcher: ^1.0.1
  yaml: ^3.1.0

dev_dependencies:
  derry: ^1.4.3
  mocktail: ^0.2.0
  test: ^1.16.0
  very_good_analysis: ^2.4.0

executables:
  brick_oven:
    path: bin/brick_oven.dart
    dart: bin/brick_oven.dart

scripts: derry.yaml

import_sorter:
  comments: false
