name: brick_oven
description:  Easily create & format brick templates with the brick_oven cli generator for mason
version: 0.1.0-dev
homepage: https://github.com/mrgnhnt96/brick_oven
repository: https://github.com/mrgnhnt96/brick_oven

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.0
  equatable: ^2.0.3
  file: ^6.1.2
  mason_logger: ^0.1.0-dev.5
  meta: ^1.7.0
  path: ^1.8.1
  pub_updater: ^0.2.2
  watcher: ^1.0.1
  yaml: ^3.1.0

dev_dependencies:
  derry: ^1.4.3
  mocktail: ^0.3.0
  test: ^1.20.1
  universal_io: ^2.0.4
  very_good_analysis: ^2.4.0

executables:
  brick_oven: brick_oven

scripts: derry.yaml

import_sorter:
  comments: false
