name: masonry
description: A sample command-line application.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'


dependencies:
  path: ^1.8.1
  watcher: ^1.0.1
  yaml: ^3.1.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: ^2.4.0

executables:
  masonry:
    path: bin/masonry.dart
    dart: bin/masonry.dart
