name: brick_oven
description:  Easily create & format brick templates with the brick_oven cli generator for mason
version: 0.1.0-dev
homepage: https://github.com/mrgnhnt96/brick_oven
repository: https://github.com/mrgnhnt96/brick_oven

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  args: ^2.3.1
  autoequal: ^0.5.0
  equatable: ^2.0.5
  file: ^6.1.4
  mason_logger: ^0.2.2
  meta: ^1.8.0
  path: ^1.8.2
  pub_updater: ^0.2.2
  usage: ^4.1.0
  watcher: ^1.0.2
  yaml: ^3.1.1

dev_dependencies:
  autoequal_gen: ^0.5.0
  build_runner: ^2.3.2
  build_version: ^2.1.1
  derry: ^1.4.3
  mocktail: ^0.3.0
  test: ^1.22.0
  universal_io: ^2.0.4
  very_good_analysis: ^3.1.0
  very_good_cli: ^0.8.5

executables:
  brick_oven: brick_oven

scripts: derry.yaml

import_sorter:
  comments: false
